name: LoRA for Retrieval CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  USING_GITHUB_ACTIONS: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with Python ${{ matrix.python-version }}
        run: |
          pytest --cov-fail-under=42